from domain.exceptions.domain_exception import DomainException


class ConfigException(DomainException):
    pass
