from domain.exceptions.domain_exception import DomainException


class SecondsException(DomainException):
    pass
